#!/bin/bash

show_power_menu() {
  local menu_options="\u200B Lock
\u200C󰤄 Suspend
\u200D Relaunch
\u2060󰜉 Restart
\u2063󰐥 Shutdown"
  local selection=$(echo -e "$menu_options" | wofi --show dmenu --prompt "Power options" --width 150 --height 195 -O alphabetical)

  case "$selection" in
  *Lock*) hyprlock ;;
  *Shutdown*) systemctl suspend ;;
  *Relaunch*) hyprctl dispatch exit ;;
  *Restart*) systemctl reboot ;;
  *Shutdown*) systemctl poweroff ;;
  esac
}

show_power_menu

